### ISSUE TITLE
window平台如何进行安装？

### ISSUE THREAD

**Issue by SophieRoyal** [ijson/in-blog-boot#1]
我看了你脚本只有Linux下运行教程。window是否只需要修改start.sh变成bat运行？

**Comment by cuiyongxu** [comment]
window启动脚本会在节后提供(2020年2月2日左右)一下,届时会在1.1.0分支编写,编写完会在此提醒您,谢谢您的支持!

**Comment by SophieRoyal** [comment]
hallo，你版本更新了么？我打算今天部署



在 2020-01-25 01:35:26，"cuiyongxu" <notifications@github.com> 写道：

window启动脚本会在节后提供(2020年2月8日左右)一下,届时会在1.1.0分支编写,谢谢您的支持

**Comment by cuiyongxu** [comment]
已处理  执行start.bat 即可执行
