### ISSUE TITLE
前后端数据不一致（数据滞后）

### ISSUE THREAD

**Issue by zybrcwb** [ijson/in-blog-boot#3]
在后台删除一篇文章 前台统计没有更新 标签没更新。
![1](https://user-images.githubusercontent.com/12710543/75513194-10339480-5a2f-11ea-81d5-1fb2f8e697d4.png)
![2](https://user-images.githubusercontent.com/12710543/75513200-16c20c00-5a2f-11ea-9021-bda43185f741.png)

需要等一段时间然后显示正常。（数据滞后很严重）

**Comment by cuiyongxu** [comment]
![image](https://user-images.githubusercontent.com/10216673/75597055-4411c700-5ace-11ea-8b34-ca2bba94d179.png)
![image](https://user-images.githubusercontent.com/10216673/75597079-5d1a7800-5ace-11ea-8f29-e0a7976b8c2b.png)


此处数值10分钟刷新一次,可以手动将缓存关闭
