### ISSUE TITLE
这个依赖是干嘛的 没有在github发布出来

### ISSUE THREAD

**Issue by zybrcwb** [ijson/in-blog-boot#4]
<dependency>
            <groupId>com.ijson</groupId>
            <artifactId>in-rest-proxy</artifactId>
            <version>1.0.3</version>
        </dependency>
这个依赖是干嘛的 没有发布出来

**Comment by zybrcwb** [comment]
看了下这个com.ijson in-rest-proxy 1.0.3 这个是你写自己封装的restful的java工具类。这种类建议在说明里说明在github下载到本地maven仓库 不然中央仓库可能下载不到的

**Comment by cuiyongxu** [comment]
![image](https://user-images.githubusercontent.com/10216673/75597122-8c30e980-5ace-11ea-8327-43b8854e5710.png)

这个jar 是2月发布过的 你可以在尝试刷新几次
